= README

== Installation
. Install latest JDK 8
. Install latest Gradle
. Use Gradle wrapper to run the app between different operating systems.
. Build the project with `./gradlew build` on Unix based systems OR `gradlew.bat build` on Windows, as a result `BUILD SUCCESSFUL` message should appear.
. Launch it with the task `run` like `./gradlew run`.

The main CLI response should look like this:
....
-------------------------------
Welcome to Xml phone list 2000!
-------------------------------

Please choose an action:
(d)isplay current items
(n)ew item
(s)ave items to file
(t)est data

> Building 75% > :run
....

== Tested on following versions

.Java on OS X
....
java version "1.8.0_65"
Java(TM) SE Runtime Environment (build 1.8.0_65-b17)
Java HotSpot(TM) 64-Bit Server VM (build 25.65-b01, mixed mode)
....

.Gradle version
....
------------------------------------------------------------
Gradle 1.11
------------------------------------------------------------

Build time:   2014-02-11 11:34:39 UTC
Build number: none
Revision:     a831fa866d46cbee94e61a09af15f9dd95987421

Groovy:       1.8.6
Ant:          Apache Ant(TM) version 1.9.2 compiled on July 8 2013
Ivy:          2.2.0
JVM:          1.8.0_65 (Oracle Corporation 25.65-b01)
OS:           Mac OS X 10.11.2 x86_64
....
